sudo: required
services:
    - docker
before_install:
    - docker build -t sandipansahana/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run sandipansahana/react-test npm run test -- --coverage
    
after_success:
    - docker build -t sandipansahana/multi-client ./client
    - docker build -t sandipansahana/multi-nginx ./nginx
    - docker build -t sandipansahana/multi-server ./server
    - docker build -t sandipansahana/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sandipansahana/multi-client 
    - docker push sandipansahana/multi-nginx
    - docker push sandipansahana/multi-server 
    - docker push sandipansahana/multi-worker 